# Generated by Django 5.2.15 on 2026-06-12 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salepayment',
            options={'ordering': ['payment_date', 'created_at']},
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_production', 'In Production'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='payment_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
