# Generated by Django 5.2.15 on 2026-06-13 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('sales', '0002_alter_salepayment_options_sale_delivery_date_and_more'),
        ('tenants', '0002_businesssettings_invoice_include_branch_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoicesequence',
            name='uniq_invoice_sequence',
        ),
        migrations.AlterField(
            model_name='invoicesequence',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddConstraint(
            model_name='invoicesequence',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('business', 'branch', 'year'), name='uniq_invoice_sequence_branch'),
        ),
        migrations.AddConstraint(
            model_name='invoicesequence',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('business', 'year'), name='uniq_invoice_sequence_global'),
        ),
    ]
