# Generated by Django 5.2.15 on 2026-07-13 19:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_estimated_adult_fabric_and_more'),
        ('sales', '0005_sale_priority_saleitem_garment_classification'),
        ('tenants', '0004_businesssettings_more_option_label_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='actual_fabric_used',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Workshop-recorded actual fabric consumption in meters.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999999.999'))], verbose_name='Actual Fabric Used'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='estimated_fabric',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Persisted estimated fabric consumption in meters.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999999.999'))], verbose_name='Estimated Fabric'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_fabric__isnull', True), ('estimated_fabric__gte', 0), _connector='OR'), name='saleitem_estimated_fabric_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('actual_fabric_used__isnull', True), ('actual_fabric_used__gte', 0), _connector='OR'), name='saleitem_actual_fabric_nonnegative'),
        ),
    ]
