# Generated by Django 5.2.15 on 2026-08-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customerfamilymember'),
        ('sales', '0010_saleitem_customer_supplied_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='family_member',
            field=models.ForeignKey(blank=True, help_text='Optional wearer for this tailoring line; null means the main customer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='customers.customerfamilymember'),
        ),
    ]
