"""Nexa backup engine foundations through the Phase 2J async boundary.

The public surface remains deliberately non-operational. It exposes typed
contracts, immutable planning metadata, and central availability guards.
"""

from .availability import (
    ASYNC_EXECUTION_BOUNDARY_READY,
    CANONICAL_MANIFEST_PROVIDER_READY,
    DETERMINISTIC_PACKAGE_PROVIDER_READY,
    DURABLE_STORAGE_PROVIDER_READY,
    ENCRYPTED_ARTIFACT_PROVIDER_READY,
    INDEPENDENT_PACKAGE_VERIFIER_READY,
    MEDIA_CAPTURE_PROVIDER_READY,
    PRODUCTION_DURABLE_STORAGE_PROVIDER_READY,
    PRODUCTION_KEY_PROVIDER_READY,
    RESTORE_ASYNC_EXECUTION_BOUNDARY_READY,
    RETENTION_ENGINE_READY,
    RUNTIME_COMPOSITION_READY,
    RUNTIME_ORCHESTRATOR_READY,
    SCHEDULE_DISPATCHER_READY,
    SQLITE_SNAPSHOT_PROVIDER_READY,
    TENANT_LOGICAL_EXPORT_PROVIDER_READY,
    assert_real_execution_available,
    async_configuration_ready,
    get_engine_capability,
    real_execution_available,
    restore_async_configuration_ready,
    restore_execution_available,
    restore_runtime_configuration_ready,
)
from .canonical_manifest import CanonicalManifestProvider
from .context import ActorIdentitySnapshot, BackupExecutionContext
from .contracts import (
    DurableBackupStorageProvider,
    EncryptedArtifactReference,
    EncryptedArtifactRequest,
    EncryptedArtifactResult,
    PackageBuildRequest,
    PackageBuildResult,
    PackageCompatibilityStatus,
    PackageVerificationRequest,
    PackageVerificationResult,
    Phase2D1Request,
    Phase2D1Result,
    Phase2D2Request,
    Phase2D2Result,
    RestoreReadinessResult,
    StoredBackupObjectReference,
    StoredBackupObjectRequest,
    StoredBackupObjectResult,
    StoredObjectDurabilityState,
    StoredObjectVerificationState,
    VerificationIssue,
    VerificationReference,
)
from .deterministic_package import DeterministicPackageProvider
from .durable_storage import LocalPrivateDurableStorageProvider
from .durable_storage_policy import DurableStoragePolicy
from .encrypted_artifact import EncryptedArtifactProvider, RewrappedArtifactKeyResult
from .encryption_policy import EncryptionPolicy
from .exceptions import BackupEngineDisabled, BackupEngineError
from .key_management import (
    AwsKmsKeyEncryptionProvider,
    KekProvider,
    KeyEncryptionProvider,
    KeyEncryptionProviderRegistry,
    LocalConfiguredKekProvider,
    WrappedDek,
)
from .key_rotation import publish_rewrapped_key_metadata
from .logical_export import (
    SQLiteLogicalComponentExporter,
    export_snapshot_components,
)
from .media_capture import LocalFilesystemMediaCaptureProvider
from .orchestration import prepare_backup_execution
from .package_verification import IndependentPackageVerifier
from .phase2d1 import Phase2D1Coordinator
from .phase2d2 import Phase2D2Coordinator
from .pipeline import BackupExecutionPlan, PipelineStage
from .retention import (
    BackupRetentionClass,
    RetentionAuditEvent,
    RetentionAuditEventType,
    RetentionCandidate,
    RetentionEngine,
    RetentionExecutionResult,
    RetentionExecutionState,
    RetentionPlan,
    RetentionPlanReference,
    RetentionSkipReason,
)
from .retention_policy import RetentionPolicy
from .runtime import (
    BackupExecutionCoordinator,
    BackupExecutionRequest,
    BackupExecutionResult,
    FinalStoredObjectEvidence,
    RuntimeProviderStack,
    RuntimeRetentionOutcome,
    build_runtime_provider_stack,
    request_backup_execution,
)
from .s3_storage import (
    S3_DURABLE_STORAGE_BACKEND_IDENTIFIER,
    S3_DURABLE_STORAGE_PROVIDER_IDENTIFIER,
    S3CompatibleDurableStorageProvider,
    S3StorageConfiguration,
)
from .sqlite_snapshot import SQLiteSnapshotProvider
from .storage_registry import (
    DurableStorageProviderRegistry,
    build_storage_provider_registry,
)

__all__ = [
    "ActorIdentitySnapshot",
    "ASYNC_EXECUTION_BOUNDARY_READY",
    "BackupEngineDisabled",
    "BackupEngineError",
    "BackupExecutionContext",
    "BackupExecutionCoordinator",
    "BackupExecutionPlan",
    "BackupExecutionRequest",
    "BackupExecutionResult",
    "BackupRetentionClass",
    "AwsKmsKeyEncryptionProvider",
    "CANONICAL_MANIFEST_PROVIDER_READY",
    "CanonicalManifestProvider",
    "DETERMINISTIC_PACKAGE_PROVIDER_READY",
    "DeterministicPackageProvider",
    "DURABLE_STORAGE_PROVIDER_READY",
    "DurableBackupStorageProvider",
    "DurableStoragePolicy",
    "ENCRYPTED_ARTIFACT_PROVIDER_READY",
    "EncryptedArtifactProvider",
    "EncryptedArtifactReference",
    "EncryptedArtifactRequest",
    "EncryptedArtifactResult",
    "EncryptionPolicy",
    "INDEPENDENT_PACKAGE_VERIFIER_READY",
    "IndependentPackageVerifier",
    "LocalFilesystemMediaCaptureProvider",
    "LocalConfiguredKekProvider",
    "LocalPrivateDurableStorageProvider",
    "KekProvider",
    "KeyEncryptionProvider",
    "KeyEncryptionProviderRegistry",
    "MEDIA_CAPTURE_PROVIDER_READY",
    "PRODUCTION_DURABLE_STORAGE_PROVIDER_READY",
    "PRODUCTION_KEY_PROVIDER_READY",
    "PackageBuildRequest",
    "PackageBuildResult",
    "PackageCompatibilityStatus",
    "PackageVerificationRequest",
    "PackageVerificationResult",
    "Phase2D1Coordinator",
    "Phase2D1Request",
    "Phase2D1Result",
    "Phase2D2Coordinator",
    "Phase2D2Request",
    "Phase2D2Result",
    "PipelineStage",
    "RestoreReadinessResult",
    "RewrappedArtifactKeyResult",
    "RETENTION_ENGINE_READY",
    "RUNTIME_COMPOSITION_READY",
    "RetentionAuditEvent",
    "RetentionAuditEventType",
    "RetentionCandidate",
    "RetentionEngine",
    "RetentionExecutionResult",
    "RetentionExecutionState",
    "RetentionPlan",
    "RetentionPlanReference",
    "RetentionPolicy",
    "RetentionSkipReason",
    "RUNTIME_ORCHESTRATOR_READY",
    "RESTORE_ASYNC_EXECUTION_BOUNDARY_READY",
    "SCHEDULE_DISPATCHER_READY",
    "RuntimeProviderStack",
    "RuntimeRetentionOutcome",
    "SQLITE_SNAPSHOT_PROVIDER_READY",
    "SQLiteSnapshotProvider",
    "SQLiteLogicalComponentExporter",
    "S3CompatibleDurableStorageProvider",
    "S3StorageConfiguration",
    "S3_DURABLE_STORAGE_BACKEND_IDENTIFIER",
    "S3_DURABLE_STORAGE_PROVIDER_IDENTIFIER",
    "TENANT_LOGICAL_EXPORT_PROVIDER_READY",
    "StoredBackupObjectReference",
    "StoredBackupObjectRequest",
    "StoredBackupObjectResult",
    "StoredObjectDurabilityState",
    "StoredObjectVerificationState",
    "VerificationIssue",
    "VerificationReference",
    "WrappedDek",
    "assert_real_execution_available",
    "async_configuration_ready",
    "get_engine_capability",
    "build_runtime_provider_stack",
    "build_storage_provider_registry",
    "prepare_backup_execution",
    "publish_rewrapped_key_metadata",
    "real_execution_available",
    "restore_async_configuration_ready",
    "restore_execution_available",
    "restore_runtime_configuration_ready",
    "request_backup_execution",
    "export_snapshot_components",
    "FinalStoredObjectEvidence",
    "DurableStorageProviderRegistry",
]
