"""Stable sanitized activity event names for Phase 2A planning."""

EXECUTION_PLAN_REQUESTED = "backup.execution_plan_requested"
EXECUTION_PLAN_CREATED = "backup.execution_plan_created"
EXECUTION_BLOCKED = "backup.execution_blocked"
WORKSPACE_CREATED = "backup.workspace_created"
WORKSPACE_CLEANED = "backup.workspace_cleaned"
COMPONENT_PLAN_RESOLVED = "backup.component_plan_resolved"
ENGINE_DISABLED = "backup.engine_disabled"
SNAPSHOT_STARTED = "backup.snapshot_started"
SNAPSHOT_CREATED = "backup.snapshot_created"
SNAPSHOT_FAILED = "backup.snapshot_failed"
SNAPSHOT_VALIDATION_FAILED = "backup.snapshot_validation_failed"
SNAPSHOT_CLEANED = "backup.snapshot_cleaned"
