"""Stable sanitized activity event names for Phase 2A planning."""

EXECUTION_PLAN_REQUESTED = "backup.execution_plan_requested"
EXECUTION_PLAN_CREATED = "backup.execution_plan_created"
EXECUTION_BLOCKED = "backup.execution_blocked"
WORKSPACE_CREATED = "backup.workspace_created"
WORKSPACE_CLEANED = "backup.workspace_cleaned"
COMPONENT_PLAN_RESOLVED = "backup.component_plan_resolved"
ENGINE_DISABLED = "backup.engine_disabled"
SNAPSHOT_STARTED = "backup.snapshot_started"
SNAPSHOT_CREATED = "backup.snapshot_created"
SNAPSHOT_FAILED = "backup.snapshot_failed"
SNAPSHOT_VALIDATION_FAILED = "backup.snapshot_validation_failed"
SNAPSHOT_CLEANED = "backup.snapshot_cleaned"
COMPONENT_EXPORT_STARTED = "backup.component_export_started"
COMPONENT_EXPORT_COMPLETED = "backup.component_export_completed"
COMPONENT_EXPORT_FAILED = "backup.component_export_failed"
COMPONENT_EXPORT_CLEANED = "backup.component_export_cleaned"
LOGICAL_EXPORT_BATCH_COMPLETED = "backup.logical_export_batch_completed"
LOGICAL_EXPORT_BATCH_FAILED = "backup.logical_export_batch_failed"
SNAPSHOT_CLEANED_AFTER_EXPORT = "backup.snapshot_cleaned_after_export"
SNAPSHOT_CLEANUP_AFTER_EXPORT_FAILED = "backup.snapshot_cleanup_after_export_failed"
BACKUP_EXECUTION_STARTED = "backup.execution_started"
BACKUP_SNAPSHOT_COMPLETED = "backup.snapshot_completed"
BACKUP_EXPORT_COMPLETED = "backup.export_completed"
BACKUP_MANIFEST_COMPLETED = "backup.manifest_completed"
BACKUP_PACKAGE_COMPLETED = "backup.package_completed"
BACKUP_VERIFIED = "backup.verified"
BACKUP_ENCRYPTED = "backup.encrypted"
BACKUP_DURABLE_STORED = "backup.durable_stored"
BACKUP_COMPLETED = "backup.completed"
BACKUP_FAILED = "backup.failed"
BACKUP_WORKSPACE_CLEANUP_DEFERRED = "backup.workspace_cleanup_deferred"
BACKUP_SCHEDULE_DISPATCHED = "backup.schedule_dispatched"
RETENTION_COMPLETED = "retention.completed"
RETENTION_PARTIAL = "retention.partial"
RETENTION_FAILED = "retention.failed"
RETENTION_HISTORICAL_EVIDENCE_DEFERRED = (
    "retention.historical_evidence_deferred"
)
RESTORE_PREFLIGHT_STARTED = "restore.preflight_started"
RESTORE_DURABLE_OBJECT_VALIDATED = "restore.durable_object_validated"
RESTORE_DECRYPTED = "restore.decrypted"
RESTORE_PACKAGE_VERIFIED = "restore.package_verified"
RESTORE_COMPATIBILITY_CHECKED = "restore.compatibility_checked"
RESTORE_PREFLIGHT_READY = "restore.preflight_ready"
RESTORE_PREFLIGHT_FAILED = "restore.preflight_failed"
