"""Stable sanitized activity event names for Phase 2A planning."""

EXECUTION_PLAN_REQUESTED = "backup.execution_plan_requested"
EXECUTION_PLAN_CREATED = "backup.execution_plan_created"
EXECUTION_BLOCKED = "backup.execution_blocked"
WORKSPACE_CREATED = "backup.workspace_created"
WORKSPACE_CLEANED = "backup.workspace_cleaned"
COMPONENT_PLAN_RESOLVED = "backup.component_plan_resolved"
ENGINE_DISABLED = "backup.engine_disabled"
SNAPSHOT_STARTED = "backup.snapshot_started"
SNAPSHOT_CREATED = "backup.snapshot_created"
SNAPSHOT_FAILED = "backup.snapshot_failed"
SNAPSHOT_VALIDATION_FAILED = "backup.snapshot_validation_failed"
SNAPSHOT_CLEANED = "backup.snapshot_cleaned"
COMPONENT_EXPORT_STARTED = "backup.component_export_started"
COMPONENT_EXPORT_COMPLETED = "backup.component_export_completed"
COMPONENT_EXPORT_FAILED = "backup.component_export_failed"
COMPONENT_EXPORT_CLEANED = "backup.component_export_cleaned"
LOGICAL_EXPORT_BATCH_COMPLETED = "backup.logical_export_batch_completed"
LOGICAL_EXPORT_BATCH_FAILED = "backup.logical_export_batch_failed"
SNAPSHOT_CLEANED_AFTER_EXPORT = "backup.snapshot_cleaned_after_export"
SNAPSHOT_CLEANUP_AFTER_EXPORT_FAILED = "backup.snapshot_cleanup_after_export_failed"
