"""Explicit Phase 2C logical-export specifications for shared tenant data."""

from apps.core.permissions import ALL_PERMISSION_CODES

from .logical_export_registry import (
    IdentityKind,
    JsonPolicy,
    ModelExportSpec,
    OmissionReason,
    json_field,
    many_to_many,
    omit,
    relation,
)

LOGICAL_EXPORT_SPECS_SHARED = (
    ModelExportSpec(
        model_label="tenants.Business",
        component_key="shared.tenant_identity",
        identity_kind=IdentityKind.PUBLIC_UUID,
        identity_field="public_id",
        ownership_field=None,
        scalar_fields=(
            "created_at",
            "updated_at",
            "name",
            "legal_name",
            "email",
            "phone",
            "whatsapp",
            "website",
            "address",
            "city",
            "state",
            "postal_code",
            "country",
            "timezone",
            "commercial_registration",
            "tax_registration_number",
            "currency_code",
            "currency_symbol",
            "currency_precision",
            "date_format",
            "business_category",
            "default_language",
            "financial_year_start_month",
            "is_active",
            "suspended_at",
            "suspension_reason",
            "reactivated_at",
            "onboarding_completed",
            "onboarding_banner_dismissed",
        ),
        relation_fields=(
            relation("owner", "accounts.User", nullable=False),
            relation("suspended_by", "accounts.User", nullable=True),
            relation("reactivated_by", "accounts.User", nullable=True),
        ),
        media_fields=("logo",),
        omitted_fields=(omit("id", OmissionReason.INTERNAL_PRIMARY_KEY),),
    ),
    ModelExportSpec(
        model_label="tenants.BusinessSettings",
        component_key="shared.tenant_settings",
        identity_kind=IdentityKind.TENANT_SINGLETON,
        identity_field=None,
        ownership_field="business",
        scalar_fields=(
            "created_at",
            "updated_at",
            "vat_enabled",
            "vat_percentage",
            "vat_registration_number",
            "show_vat_on_invoice_receipt",
            "prices_include_tax",
            "show_tax_on_receipt",
            "more_option_label_1",
            "more_option_label_2",
            "more_option_label_3",
            "more_option_label_4",
            "more_option_label_5",
            "more_option_label_6",
            "more_option_label_7",
            "more_option_label_8",
            "more_option_label_9",
            "more_option_label_10",
            "more_option_label_11",
            "more_option_label_12",
            "more_option_label_13",
            "more_option_label_14",
            "more_option_label_15",
            "more_option_label_16",
            "more_option_label_17",
            "more_option_label_18",
            "more_option_label_19",
            "more_option_label_20",
            "invoice_prefix",
            "invoice_include_branch_code",
            "invoice_footer",
            "receipt_footer",
            "terms_and_conditions",
            "show_logo_on_invoice",
            "negative_stock_policy",
            "allow_sale_without_shift",
            "max_discount_percent",
            "require_customer_for_credit",
            "return_window_days",
            "expense_approval_threshold",
            "adjustment_requires_approval",
            "price_rounding",
            "notify_low_stock",
            "notify_credit_overdue",
            "notify_support_access",
        ),
        relation_fields=(
            relation(
                "shared_fabric_warehouse",
                "branches.Warehouse",
                nullable=True,
            ),
        ),
        omitted_fields=(omit("id", OmissionReason.INTERNAL_PRIMARY_KEY),),
    ),
    ModelExportSpec(
        model_label="accounts.Role",
        component_key="shared.access_control",
        identity_kind=IdentityKind.PUBLIC_UUID,
        identity_field="public_id",
        ownership_field="business",
        scalar_fields=(
            "created_at",
            "updated_at",
            "name",
            "is_owner",
            "is_system",
        ),
        json_fields=(
            json_field(
                "permissions",
                policy=JsonPolicy.SORTED_STRING_SET,
                allowed_values=tuple(ALL_PERMISSION_CODES),
            ),
        ),
        omitted_fields=(omit("id", OmissionReason.INTERNAL_PRIMARY_KEY),),
    ),
    ModelExportSpec(
        model_label="accounts.Membership",
        component_key="shared.access_control",
        identity_kind=IdentityKind.PUBLIC_UUID,
        identity_field="public_id",
        ownership_field="business",
        scalar_fields=(
            "created_at",
            "updated_at",
            "is_active",
        ),
        relation_fields=(
            relation("user", "accounts.User", nullable=False),
            relation("role", "accounts.Role", nullable=False),
        ),
        many_to_many_fields=(many_to_many("branches", "branches.Branch"),),
        omitted_fields=(omit("id", OmissionReason.INTERNAL_PRIMARY_KEY),),
    ),
    ModelExportSpec(
        model_label="branches.Branch",
        component_key="shared.locations",
        identity_kind=IdentityKind.PUBLIC_UUID,
        identity_field="public_id",
        ownership_field="business",
        scalar_fields=(
            "created_at",
            "updated_at",
            "name",
            "code",
            "usage_type",
            "address",
            "phone",
            "email",
            "invoice_prefix",
            "receipt_footer",
            "is_head_office",
            "is_active",
        ),
        relation_fields=(relation("manager", "accounts.User", nullable=True),),
        omitted_fields=(omit("id", OmissionReason.INTERNAL_PRIMARY_KEY),),
    ),
    ModelExportSpec(
        model_label="branches.Warehouse",
        component_key="shared.locations",
        identity_kind=IdentityKind.PUBLIC_UUID,
        identity_field="public_id",
        ownership_field="business",
        scalar_fields=(
            "created_at",
            "updated_at",
            "name",
            "code",
            "address",
            "is_default",
            "is_active",
        ),
        relation_fields=(
            relation("branch", "branches.Branch", nullable=True),
            relation("manager", "accounts.User", nullable=True),
        ),
        omitted_fields=(omit("id", OmissionReason.INTERNAL_PRIMARY_KEY),),
    ),
)
