"""Explicit Phase 2C logical-export specifications for POS components."""

from .logical_export_registry import (
    IdentityKind,
    JsonPolicy,
    ModelExportSpec,
    OmissionReason,
    ScalarPolicy,
    json_field,
    omit,
    relation,
)

_TIMESTAMP_FIELDS = ("created_at", "updated_at")
_INTERNAL_ID_OMISSION = (omit("id", OmissionReason.INTERNAL_PRIMARY_KEY),)
_CUSTOMER_MORE_OPTION_KEYS = tuple(str(index) for index in range(1, 21))
_TAILORING_DETAIL_KEYS = (
    "design_type",
    "daraz_details",
    "vip_3d_design",
    "computer_design",
    "customer_notes",
    "workshop_notes",
)


def _tenant_spec(
    *,
    model_label,
    component_key,
    scalar_fields=(),
    relation_fields=(),
    json_fields=(),
    media_fields=(),
    omitted_fields=(),
    scalar_policies=(),
    validators=(),
):
    return ModelExportSpec(
        model_label=model_label,
        component_key=component_key,
        identity_kind=IdentityKind.PUBLIC_UUID,
        identity_field="public_id",
        ownership_field="business",
        scalar_fields=_TIMESTAMP_FIELDS + tuple(scalar_fields),
        relation_fields=tuple(relation_fields),
        json_fields=tuple(json_fields),
        media_fields=tuple(media_fields),
        omitted_fields=_INTERNAL_ID_OMISSION + tuple(omitted_fields),
        scalar_policies=tuple(scalar_policies),
        validators=tuple(validators),
    )


LOGICAL_EXPORT_SPECS_POS = (
    _tenant_spec(
        model_label="catalog.Category",
        component_key="pos.catalog",
        scalar_fields=("name", "is_active"),
        relation_fields=(relation("parent", "catalog.Category", nullable=True),),
    ),
    _tenant_spec(
        model_label="catalog.Brand",
        component_key="pos.catalog",
        scalar_fields=("name", "is_active"),
    ),
    _tenant_spec(
        model_label="catalog.Unit",
        component_key="pos.catalog",
        scalar_fields=(
            "name",
            "abbreviation",
            "allow_decimal",
            "is_meter",
            "is_active",
        ),
    ),
    _tenant_spec(
        model_label="catalog.TaxRate",
        component_key="pos.catalog",
        scalar_fields=("name", "rate", "is_default", "is_active"),
    ),
    _tenant_spec(
        model_label="catalog.Product",
        component_key="pos.catalog",
        scalar_fields=(
            "name",
            "internal_code",
            "sku",
            "barcode",
            "product_type",
            "purchase_price",
            "sale_price",
            "wholesale_price",
            "minimum_sale_price",
            "average_cost",
            "price_includes_tax",
            "reorder_level",
            "track_inventory",
            "allow_discount",
            "is_tailoring_item",
            "estimated_adult_fabric",
            "estimated_child_fabric",
            "description",
            "is_active",
            "is_archived",
        ),
        relation_fields=(
            relation("category", "catalog.Category", nullable=True),
            relation("brand", "catalog.Brand", nullable=True),
            relation("unit", "catalog.Unit", nullable=True),
            relation("tax_rate", "catalog.TaxRate", nullable=True),
            relation("preferred_supplier", "suppliers.Supplier", nullable=True),
        ),
        media_fields=("image",),
    ),
    _tenant_spec(
        model_label="catalog.ProductVariant",
        component_key="pos.catalog",
        scalar_fields=(
            "name",
            "sku",
            "barcode",
            "purchase_price",
            "sale_price",
            "average_cost",
            "is_active",
        ),
        relation_fields=(relation("product", "catalog.Product"),),
        json_fields=(
            json_field(
                "attributes",
                policy=JsonPolicy.FLAT_STRING_MAP,
            ),
        ),
        media_fields=("image",),
    ),
    _tenant_spec(
        model_label="customers.CustomerGroup",
        component_key="pos.customers",
        scalar_fields=("name",),
    ),
    _tenant_spec(
        model_label="customers.Customer",
        component_key="pos.customers",
        scalar_fields=(
            "code",
            "full_name",
            "mobile",
            "whatsapp",
            "email",
            "address",
            "city",
            "country",
            "tax_number",
            "credit_limit",
            "opening_balance",
            "balance",
            "store_credit",
            "loyalty_points",
            "notes",
            "is_walk_in",
            "is_active",
        ),
        relation_fields=(
            relation("home_branch", "branches.Branch", nullable=True),
            relation("group", "customers.CustomerGroup", nullable=True),
        ),
        json_fields=(
            json_field(
                "more_options",
                policy=JsonPolicy.INDEXED_STRING_MAP,
                allowed_values=_CUSTOMER_MORE_OPTION_KEYS,
            ),
        ),
    ),
    _tenant_spec(
        model_label="customers.CustomerPayment",
        component_key="pos.customers",
        scalar_fields=(
            "receipt_number",
            "kind",
            "amount",
            "reference",
            "notes",
        ),
        relation_fields=(
            relation("customer", "customers.Customer"),
            relation("branch", "branches.Branch", nullable=True),
            relation("payment_method", "sales.PaymentMethod", nullable=True),
            relation("received_by", "accounts.User", nullable=True),
            relation("shift", "registers.Shift", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="suppliers.Supplier",
        component_key="pos.suppliers",
        scalar_fields=(
            "code",
            "name",
            "contact_person",
            "mobile",
            "email",
            "address",
            "tax_number",
            "opening_balance",
            "balance",
            "payment_terms",
            "notes",
            "is_active",
        ),
    ),
    _tenant_spec(
        model_label="suppliers.SupplierPayment",
        component_key="pos.suppliers",
        scalar_fields=(
            "payment_number",
            "amount",
            "method",
            "cheque_number",
            "bank_name",
            "cheque_issue_date",
            "due_date",
            "cheque_status",
            "cleared_at",
            "reference",
            "notes",
        ),
        relation_fields=(
            relation("supplier", "suppliers.Supplier"),
            relation("purchase", "purchases.Purchase", nullable=True),
            relation("payment_method", "sales.PaymentMethod", nullable=True),
            relation("paid_by", "accounts.User", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="inventory.StockLevel",
        component_key="pos.inventory",
        scalar_fields=("quantity",),
        relation_fields=(
            relation("warehouse", "branches.Warehouse"),
            relation("product", "catalog.Product"),
            relation("variant", "catalog.ProductVariant", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="inventory.StockMovement",
        component_key="pos.inventory",
        scalar_fields=(
            "movement_type",
            "quantity",
            "unit_cost",
            "balance_after",
            "reference_type",
            "reference_id",
            "notes",
        ),
        relation_fields=(
            relation("warehouse", "branches.Warehouse"),
            relation("product", "catalog.Product"),
            relation("variant", "catalog.ProductVariant", nullable=True),
            relation("user", "accounts.User", nullable=True),
        ),
        scalar_policies=(("reference_id", ScalarPolicy.OPAQUE_BUSINESS_REFERENCE),),
        validators=("stock_movement_business_reference_matches",),
    ),
    _tenant_spec(
        model_label="inventory.StockTransfer",
        component_key="pos.inventory",
        scalar_fields=(
            "transfer_number",
            "status",
            "dispatched_at",
            "received_at",
            "notes",
        ),
        relation_fields=(
            relation("from_warehouse", "branches.Warehouse"),
            relation("to_warehouse", "branches.Warehouse"),
            relation("requested_by", "accounts.User", nullable=True),
            relation("approved_by", "accounts.User", nullable=True),
            relation("dispatched_by", "accounts.User", nullable=True),
            relation("received_by", "accounts.User", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="inventory.StockTransferItem",
        component_key="pos.inventory",
        scalar_fields=("quantity", "unit_cost"),
        relation_fields=(
            relation("transfer", "inventory.StockTransfer"),
            relation("product", "catalog.Product"),
            relation("variant", "catalog.ProductVariant", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="inventory.StockAdjustment",
        component_key="pos.inventory",
        scalar_fields=(
            "adjustment_number",
            "reason",
            "status",
            "notes",
        ),
        relation_fields=(
            relation("warehouse", "branches.Warehouse"),
            relation("created_by", "accounts.User", nullable=True),
            relation("approved_by", "accounts.User", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="inventory.StockAdjustmentItem",
        component_key="pos.inventory",
        scalar_fields=("previous_quantity", "change"),
        relation_fields=(
            relation("adjustment", "inventory.StockAdjustment"),
            relation("product", "catalog.Product"),
            relation("variant", "catalog.ProductVariant", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="inventory.StockCount",
        component_key="pos.inventory",
        scalar_fields=("count_number", "status", "notes"),
        relation_fields=(
            relation("warehouse", "branches.Warehouse"),
            relation("created_by", "accounts.User", nullable=True),
            relation("approved_by", "accounts.User", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="inventory.StockCountItem",
        component_key="pos.inventory",
        scalar_fields=("expected_quantity", "counted_quantity"),
        relation_fields=(
            relation("count", "inventory.StockCount"),
            relation("product", "catalog.Product"),
            relation("variant", "catalog.ProductVariant", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="purchases.Purchase",
        component_key="pos.purchases",
        scalar_fields=(
            "purchase_number",
            "supplier_invoice_number",
            "purchase_date",
            "due_date",
            "status",
            "subtotal",
            "discount_amount",
            "tax_amount",
            "shipping_cost",
            "other_charges",
            "total",
            "amount_paid",
            "notes",
        ),
        relation_fields=(
            relation("supplier", "suppliers.Supplier"),
            relation("branch", "branches.Branch"),
            relation("warehouse", "branches.Warehouse"),
            relation("created_by", "accounts.User", nullable=True),
        ),
        media_fields=("attachment",),
    ),
    _tenant_spec(
        model_label="purchases.PurchaseItem",
        component_key="pos.purchases",
        scalar_fields=(
            "product_name",
            "quantity_ordered",
            "quantity_received",
            "unit_cost",
            "discount_amount",
            "tax_amount",
            "line_total",
        ),
        relation_fields=(
            relation("purchase", "purchases.Purchase"),
            relation("product", "catalog.Product"),
            relation("variant", "catalog.ProductVariant", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="purchases.PurchaseReturn",
        component_key="pos.purchases",
        scalar_fields=("return_number", "reason", "total", "notes"),
        relation_fields=(
            relation("purchase", "purchases.Purchase"),
            relation("supplier", "suppliers.Supplier"),
            relation("warehouse", "branches.Warehouse"),
            relation("processed_by", "accounts.User", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="purchases.PurchaseReturnItem",
        component_key="pos.purchases",
        scalar_fields=("quantity", "unit_cost", "line_total"),
        relation_fields=(
            relation("purchase_return", "purchases.PurchaseReturn"),
            relation("purchase_item", "purchases.PurchaseItem"),
        ),
    ),
    _tenant_spec(
        model_label="registers.CashRegister",
        component_key="pos.registers",
        scalar_fields=("name", "code", "receipt_printer", "is_active"),
        relation_fields=(relation("branch", "branches.Branch"),),
    ),
    _tenant_spec(
        model_label="registers.Shift",
        component_key="pos.registers",
        scalar_fields=(
            "status",
            "opened_at",
            "opening_cash",
            "opening_notes",
            "closed_at",
            "expected_cash",
            "actual_cash",
            "difference",
            "closing_notes",
            "reopened_count",
        ),
        relation_fields=(
            relation("register", "registers.CashRegister"),
            relation("branch", "branches.Branch"),
            relation("cashier", "accounts.User"),
            relation("approved_by", "accounts.User", nullable=True),
        ),
        json_fields=(
            json_field(
                "denominations",
                policy=JsonPolicy.DENOMINATION_MAP,
            ),
        ),
    ),
    _tenant_spec(
        model_label="sales.PaymentMethod",
        component_key="pos.sales",
        scalar_fields=("name", "kind", "is_active", "is_system"),
    ),
    _tenant_spec(
        model_label="sales.InvoiceSequence",
        component_key="pos.sales",
        scalar_fields=("year", "last_number"),
        relation_fields=(relation("branch", "branches.Branch", nullable=True),),
    ),
    _tenant_spec(
        model_label="sales.Sale",
        component_key="pos.sales",
        scalar_fields=(
            "invoice_number",
            "status",
            "priority",
            "sale_date",
            "delivery_date",
            "delivery_status",
            "subtotal",
            "discount_amount",
            "tax_amount",
            "rounding",
            "total",
            "amount_paid",
            "change_due",
            "total_cost",
            "gross_profit",
            "notes",
            "reprint_count",
            "voided_at",
            "void_reason",
        ),
        relation_fields=(
            relation("branch", "branches.Branch"),
            relation("warehouse", "branches.Warehouse"),
            relation("register", "registers.CashRegister", nullable=True),
            relation("shift", "registers.Shift", nullable=True),
            relation("cashier", "accounts.User"),
            relation("salesperson", "accounts.User", nullable=True),
            relation("customer", "customers.Customer"),
            relation("voided_by", "accounts.User", nullable=True),
        ),
        omitted_fields=(omit("checkout_token", OmissionReason.DESTINATION_LOCAL_TOKEN),),
    ),
    _tenant_spec(
        model_label="sales.SaleItem",
        component_key="pos.sales",
        scalar_fields=(
            "product_name",
            "sku",
            "quantity",
            "unit_price",
            "discount_amount",
            "tax_rate",
            "tax_amount",
            "line_total",
            "unit_cost",
            "gross_profit",
            "returned_quantity",
            "garment_classification",
            "collection_type",
            "estimated_fabric",
            "actual_fabric_used",
            "fabric_meter_used",
        ),
        relation_fields=(
            relation("sale", "sales.Sale"),
            relation("product", "catalog.Product"),
            relation("variant", "catalog.ProductVariant", nullable=True),
            relation("stock_warehouse", "branches.Warehouse", nullable=True),
        ),
        json_fields=(
            json_field(
                "tailoring_details",
                policy=JsonPolicy.FLAT_STRING_MAP,
                allowed_values=_TAILORING_DETAIL_KEYS,
            ),
        ),
    ),
    _tenant_spec(
        model_label="sales.SalePayment",
        component_key="pos.sales",
        scalar_fields=("amount", "payment_date", "reference", "notes"),
        relation_fields=(
            relation("sale", "sales.Sale"),
            relation("method", "sales.PaymentMethod"),
            relation("received_by", "accounts.User", nullable=True),
            relation("shift", "registers.Shift", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="sales.SaleReturn",
        component_key="pos.sales",
        scalar_fields=(
            "return_number",
            "reason",
            "refund_method",
            "refund_amount",
            "restock",
            "notes",
        ),
        relation_fields=(
            relation("sale", "sales.Sale"),
            relation("customer", "customers.Customer"),
            relation("branch", "branches.Branch"),
            relation("warehouse", "branches.Warehouse"),
            relation("processed_by", "accounts.User", nullable=True),
            relation("shift", "registers.Shift", nullable=True),
        ),
    ),
    _tenant_spec(
        model_label="sales.SaleReturnItem",
        component_key="pos.sales",
        scalar_fields=(
            "quantity",
            "refund_per_unit",
            "line_refund",
            "restocked",
        ),
        relation_fields=(
            relation("sale_return", "sales.SaleReturn"),
            relation("sale_item", "sales.SaleItem"),
        ),
    ),
    _tenant_spec(
        model_label="expenses.ExpenseCategory",
        component_key="pos.expenses",
        scalar_fields=("name", "is_active"),
        relation_fields=(relation("parent", "expenses.ExpenseCategory", nullable=True),),
    ),
    _tenant_spec(
        model_label="expenses.RecurringExpenseTemplate",
        component_key="pos.expenses",
        scalar_fields=(
            "name",
            "default_amount",
            "due_day",
            "start_date",
            "end_date",
            "notes",
            "is_active",
        ),
        relation_fields=(
            relation("branch", "branches.Branch", nullable=True),
            relation("category", "expenses.ExpenseCategory"),
        ),
    ),
    _tenant_spec(
        model_label="expenses.Expense",
        component_key="pos.expenses",
        scalar_fields=(
            "expense_number",
            "expense_date",
            "payee",
            "amount",
            "tax_amount",
            "reference",
            "description",
            "status",
            "generated_for_month",
        ),
        relation_fields=(
            relation("branch", "branches.Branch"),
            relation("category", "expenses.ExpenseCategory"),
            relation("supplier", "suppliers.Supplier", nullable=True),
            relation("payment_method", "sales.PaymentMethod", nullable=True),
            relation("shift", "registers.Shift", nullable=True),
            relation("created_by", "accounts.User", nullable=True),
            relation("approved_by", "accounts.User", nullable=True),
            relation(
                "recurring_template",
                "expenses.RecurringExpenseTemplate",
                nullable=True,
            ),
        ),
        media_fields=("attachment",),
    ),
)
