# Generated by Django 5.2.15 on 2026-06-11 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('registers', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.paymentmethod'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='registers.shift'),
        ),
        migrations.AddConstraint(
            model_name='customergroup',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='uniq_customer_group_per_business'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'full_name'], name='customers_c_busines_c0b759_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'mobile'], name='customers_c_busines_79cd08_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='uniq_customer_code_per_business'),
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.UniqueConstraint(fields=('business', 'receipt_number'), name='uniq_customer_receipt_per_business'),
        ),
    ]
