# Generated by Django 5.2.15 on 2026-06-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='more_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
