# Generated by Django 5.2.15 on 2026-07-19 14:07

import django.db.models.deletion
from django.db import migrations, models


def assign_safe_customer_branches(apps, schema_editor):
    """Backfill only deterministic ownership and provision per-branch walk-ins."""
    Branch = apps.get_model("branches", "Branch")
    Customer = apps.get_model("customers", "Customer")

    business_ids = (
        Branch.objects.filter(is_active=True)
        .values_list("business_id", flat=True)
        .distinct()
    )
    for business_id in business_ids.iterator():
        branches = list(
            Branch.objects.filter(business_id=business_id, is_active=True)
            .order_by("id")
        )
        if len(branches) == 1:
            branch = branches[0]
            Customer.objects.filter(
                business_id=business_id,
                home_branch__isnull=True,
                is_walk_in=False,
            ).update(home_branch=branch)
            # Historical data should normally contain one global walk-in. If
            # malformed legacy data contains more, assign only the canonical
            # first record so the new one-per-branch constraint remains safe;
            # preserve every extra record unassigned rather than deleting it.
            walk_in = Customer.objects.filter(
                business_id=business_id,
                home_branch__isnull=True,
                is_walk_in=True,
            ).order_by("id").first()
            if walk_in is not None:
                walk_in.home_branch = branch
                walk_in.save(update_fields=["home_branch"])
            continue

        # With multiple active branches ownership cannot be inferred. Preserve
        # every legacy customer (including the former global walk-in) as
        # unassigned and create an operational walk-in for each branch.
        for branch in branches:
            if Customer.objects.filter(
                business_id=business_id,
                home_branch=branch,
                is_walk_in=True,
            ).exists():
                continue
            Customer.objects.create(
                business_id=business_id,
                home_branch=branch,
                code=f"WALK-IN-{branch.code}"[:30],
                full_name=f"Walk-In Customer — {branch.name}"[:160],
                is_walk_in=True,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0003_customer_more_options'),
        ('tenants', '0004_businesssettings_more_option_label_1_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='uniq_customer_code_per_business',
        ),
        migrations.AddField(
            model_name='customer',
            name='home_branch',
            field=models.ForeignKey(blank=True, help_text='Owning operational branch. Unassigned legacy customers are owner-only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='branches.branch'),
        ),
        migrations.RunPython(assign_safe_customer_branches, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'home_branch', 'full_name'], name='customers_c_busines_5e0829_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('home_branch__isnull', False)), fields=('business', 'home_branch', 'code'), name='uniq_customer_code_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('home_branch__isnull', True)), fields=('business', 'code'), name='uniq_unassigned_customer_code'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('home_branch__isnull', False), ('is_walk_in', True)), fields=('business', 'home_branch'), name='uniq_walk_in_customer_per_branch'),
        ),
    ]
