# Generated by Django 5.2.15 on 2026-08-30 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_home_branch'),
        ('tenants', '0006_business_onboarding_banner_dismissed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('relation', models.CharField(choices=[('son', 'Son'), ('brother', 'Brother'), ('father', 'Father')], max_length=10)),
                ('more_options', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='customers.customer')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'customer', 'is_active'], name='cust_family_active_idx'), models.Index(fields=['business', 'customer', 'relation', 'name'], name='cust_family_relation_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('relation__in', ['son', 'brother', 'father'])), name='customer_family_relation_valid')],
            },
        ),
    ]
