# Generated by Django 5.2.15 on 2026-09-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sales_report_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
