from django.urls import path

from . import views

urlpatterns = [
    path("", views.report_index, name="report_index"),
    path(
        "daily-production/",
        views.daily_production_report,
        name="report_daily_production",
    ),
    path(
        "daily-production/export.xlsx",
        views.daily_production_export,
        name="report_daily_production_export",
    ),
    path(
        "daily-finished/",
        views.daily_finished_report,
        name="report_daily_finished",
    ),
    path(
        "daily-finished/export.xlsx",
        views.daily_finished_export,
        name="report_daily_finished_export",
    ),
    path(
        "daily-orders/",
        views.daily_orders_report,
        name="report_daily_orders",
    ),
    path(
        "daily-orders/export.xlsx",
        views.daily_orders_export,
        name="report_daily_orders_export",
    ),
    path(
        "monthly-orders/",
        views.monthly_orders_report,
        name="report_monthly_orders",
    ),
    path(
        "monthly-orders/export.xlsx",
        views.monthly_orders_export,
        name="report_monthly_orders_export",
    ),
    path(
        "daily-alterations/",
        views.daily_alterations_report,
        name="report_daily_alterations",
    ),
    path(
        "daily-alterations/export.xlsx",
        views.daily_alterations_export,
        name="report_daily_alterations_export",
    ),
    path(
        "monthly-alterations/",
        views.monthly_alterations_report,
        name="report_monthly_alterations",
    ),
    path(
        "monthly-alterations/export.xlsx",
        views.monthly_alterations_export,
        name="report_monthly_alterations_export",
    ),
    path(
        "monthly-production/",
        views.monthly_production_report,
        name="report_monthly_production",
    ),
    path(
        "monthly-production/export.xlsx",
        views.monthly_production_export,
        name="report_monthly_production_export",
    ),
    path(
        "attendance-summary/",
        views.attendance_summary_report,
        name="report_attendance_summary",
    ),
    path(
        "attendance-summary/export.xlsx",
        views.attendance_summary_export,
        name="report_attendance_summary_export",
    ),
    path(
        "individual-attendance/",
        views.individual_attendance_report,
        name="report_individual_attendance",
    ),
    path(
        "individual-attendance/export.xlsx",
        views.individual_attendance_export,
        name="report_individual_attendance_export",
    ),
    path(
        "salary/",
        views.salary_report,
        name="report_salary",
    ),
    path(
        "salary/export.xlsx",
        views.salary_export,
        name="report_salary_export",
    ),
]
