# Generated by Django 5.2.15 on 2026-07-24 12:51

import datetime
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_sales_report_permission'),
        ('branches', '0002_branch_usage_type'),
        ('tenants', '0006_business_onboarding_banner_dismissed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('location_type', models.CharField(choices=[('SOURCE', 'Source'), ('WORKSHOP', 'Workshop'), ('BOTH', 'Source and Workshop')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_locations', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
            ],
            options={
                'ordering': ['branch__name'],
            },
        ),
        migrations.CreateModel(
            name='WmsRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=80)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('first_shift_start', models.TimeField(default=datetime.time(10, 0))),
                ('first_shift_end', models.TimeField(default=datetime.time(13, 0))),
                ('second_shift_start', models.TimeField(default=datetime.time(16, 30))),
                ('second_shift_end', models.TimeField(default=datetime.time(22, 0))),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('default_workshop_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='wms_core.wmslocation')),
            ],
            options={
                'verbose_name_plural': 'WMS settings',
            },
        ),
        migrations.CreateModel(
            name='WmsUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_locations', models.ManyToManyField(blank=True, help_text='Empty means access to all active WMS locations.', related_name='user_access_records', to='wms_core.wmslocation')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wms_access_records', to='accounts.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_access_records', to='wms_core.wmsrole')),
            ],
            options={
                'verbose_name_plural': 'WMS user access',
            },
        ),
        migrations.AddIndex(
            model_name='wmslocation',
            index=models.Index(fields=['business', 'is_active'], name='wms_loc_business_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmslocation',
            constraint=models.UniqueConstraint(fields=('business', 'branch'), name='uniq_wms_location_branch_per_business'),
        ),
        migrations.AddConstraint(
            model_name='wmslocation',
            constraint=models.CheckConstraint(condition=models.Q(('location_type__in', ('SOURCE', 'WORKSHOP', 'BOTH'))), name='valid_wms_location_type'),
        ),
        migrations.AddIndex(
            model_name='wmsrole',
            index=models.Index(fields=['business', 'is_active'], name='wms_role_business_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsrole',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('business'), name='uniq_wms_role_name_ci_per_business'),
        ),
        migrations.AddConstraint(
            model_name='wmsrole',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='uniq_wms_role_code_per_business'),
        ),
        migrations.AddConstraint(
            model_name='wmssettings',
            constraint=models.UniqueConstraint(fields=('business',), name='uniq_wms_settings_per_business'),
        ),
        migrations.AddIndex(
            model_name='wmsuseraccess',
            index=models.Index(fields=['business', 'is_active'], name='wms_access_business_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsuseraccess',
            constraint=models.UniqueConstraint(fields=('business', 'membership'), name='uniq_wms_access_membership_per_business'),
        ),
    ]
