# Generated by Django 5.2.15 on 2026-06-11 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20)),
                ('receipt_printer', models.CharField(choices=[('80mm', '80mm thermal'), ('58mm', '58mm thermal'), ('a4', 'A4')], default='80mm', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('approved', 'Approved')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('opening_cash', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('opening_notes', models.CharField(blank=True, max_length=300)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_cash', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('denominations', models.JSONField(blank=True, null=True)),
                ('closing_notes', models.CharField(blank=True, max_length=300)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='registers.cashregister')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='uniq_register_code_per_business'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('register',), name='uniq_open_shift_per_register'),
        ),
    ]
