# Generated by Django 5.2.15 on 2026-06-11 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=60)),
                ('commercial_registration', models.CharField(blank=True, max_length=60)),
                ('tax_registration_number', models.CharField(blank=True, max_length=60)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(blank=True, max_length=10)),
                ('currency_precision', models.PositiveSmallIntegerField(default=2)),
                ('date_format', models.CharField(default='Y-m-d', max_length=20)),
                ('business_category', models.CharField(blank=True, max_length=80)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('financial_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.CharField(blank=True, max_length=255)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prices_include_tax', models.BooleanField(default=False)),
                ('show_tax_on_receipt', models.BooleanField(default=True)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_footer', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for your business!')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('show_logo_on_invoice', models.BooleanField(default=True)),
                ('negative_stock_policy', models.CharField(choices=[('block', 'Block sales when stock is insufficient'), ('warn', 'Warn but allow'), ('allow', 'Allow silently')], default='block', max_length=10)),
                ('allow_sale_without_shift', models.BooleanField(default=False)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('require_customer_for_credit', models.BooleanField(default=True)),
                ('return_window_days', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('expense_approval_threshold', models.DecimalField(decimal_places=3, default=0, help_text='Expenses above this amount require approval. 0 disables.', max_digits=14)),
                ('adjustment_requires_approval', models.BooleanField(default=False)),
                ('price_rounding', models.CharField(choices=[('none', 'No rounding'), ('nearest', 'Round total to precision')], default='nearest', max_length=10)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_credit_overdue', models.BooleanField(default=True)),
                ('notify_support_access', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.business')),
            ],
            options={
                'verbose_name_plural': 'business settings',
            },
        ),
    ]
