# Generated by Django 5.2.15 on 2026-06-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='invoice_include_branch_code',
            field=models.BooleanField(default=False, help_text='Append the branch code to invoice numbers (e.g. INV-HK-2026-000001) and number each branch separately.'),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='invoice_prefix',
            field=models.CharField(default='INV', help_text='Used for all new invoice/receipt numbers, e.g. INV → INV-2026-000001.', max_length=15),
        ),
    ]
