# Generated by Django 5.2.15 on 2026-06-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_business_reactivated_at_business_reactivated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_10',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_11',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_12',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_13',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_14',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_15',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_3',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_4',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_5',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_6',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_7',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_8',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_9',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='show_vat_on_invoice_receipt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='vat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='vat_registration_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
