# Generated by Django 5.2.15 on 2026-07-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_businesssettings_shared_fabric_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='onboarding_banner_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_16',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_17',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_18',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_19',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='more_option_label_20',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
