# Generated by Django 5.2.15 on 2026-07-24 21:44

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_business_onboarding_banner_dismissed_and_more'),
        ('wms_core', '0003_phase5_order_finish_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsWorkshopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order_reference', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('IN_PROCESS', 'In Process'), ('FINISHED_READY', 'Finished / Ready')], default='IN_PROCESS', max_length=20)),
                ('received_date', models.DateField()),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_workshop_orders_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_orders', to='wms_core.wmslocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_workshop_orders_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', 'order_reference'],
            },
        ),
        migrations.CreateModel(
            name='WmsWorkshopOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('previous_status', models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('FINISHED_READY', 'Finished / Ready')], max_length=20)),
                ('new_status', models.CharField(choices=[('IN_PROCESS', 'In Process'), ('FINISHED_READY', 'Finished / Ready')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='wms_orders.wmsworkshoporder')),
            ],
            options={
                'ordering': ['changed_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='wmsworkshoporder',
            index=models.Index(fields=['business', 'status', 'received_date'], name='wms_order_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsworkshoporder',
            index=models.Index(fields=['business', 'location', 'received_date'], name='wms_order_location_date_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsworkshoporder',
            index=models.Index(fields=['business', 'order_reference'], name='wms_order_reference_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsworkshoporder',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('order_reference'), models.F('business'), name='uniq_wms_order_reference_ci_business'),
        ),
        migrations.AddConstraint(
            model_name='wmsworkshoporder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('IN_PROCESS', 'FINISHED_READY'))), name='valid_wms_workshop_order_status'),
        ),
        migrations.AddConstraint(
            model_name='wmsworkshoporder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_date__isnull', True), ('status', 'IN_PROCESS')), models.Q(('finished_date__isnull', False), ('status', 'FINISHED_READY')), _connector='OR'), name='valid_wms_order_finished_date'),
        ),
        migrations.AddIndex(
            model_name='wmsworkshoporderstatushistory',
            index=models.Index(fields=['business', 'order', 'changed_at'], name='wms_order_history_date_idx'),
        ),
    ]
