# Generated by Django 5.2.15 on 2026-09-01 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_business_onboarding_banner_dismissed_and_more"),
        ("wms_core", "0004_phase6_alteration_complete_permission"),
        ("wms_orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wmsworkshoporder",
            name="eligible_piece_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="wmsworkshoporder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible_piece_count__isnull", True),
                    ("eligible_piece_count__gt", 0),
                    _connector="OR",
                ),
                name="valid_wms_order_piece_count",
            ),
        ),
    ]
