# Generated by Django 5.2.15 on 2026-06-11 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('percent_off', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount_off', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('extra_trial_days', models.PositiveIntegerField(default=0)),
                ('max_redemptions', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('annual_price', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('max_users', models.PositiveIntegerField(default=2)),
                ('max_warehouses', models.PositiveIntegerField(default=1)),
                ('max_products', models.PositiveIntegerField(default=0)),
                ('max_customers', models.PositiveIntegerField(default=0)),
                ('max_monthly_invoices', models.PositiveIntegerField(default=0)),
                ('storage_limit_mb', models.PositiveIntegerField(default=0)),
                ('feature_purchases', models.BooleanField(default=True)),
                ('feature_expenses', models.BooleanField(default=True)),
                ('feature_returns', models.BooleanField(default=True)),
                ('feature_transfers', models.BooleanField(default=False)),
                ('feature_advanced_reports', models.BooleanField(default=False)),
                ('feature_customer_credit', models.BooleanField(default=True)),
                ('feature_api_access', models.BooleanField(default=False)),
                ('feature_white_label', models.BooleanField(default=False)),
                ('feature_custom_roles', models.BooleanField(default=False)),
                ('feature_audit_logs', models.BooleanField(default=True)),
                ('support_level', models.CharField(default='standard', max_length=40)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace Period'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=12)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_days', models.PositiveIntegerField(default=7)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('bank_transfer', 'Bank Transfer'), ('gateway', 'Online Gateway')], default='manual', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.coupon')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
