# Generated by Django 5.2.15 on 2026-07-05 21:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def populate_payment_business(apps, schema_editor):
    SubscriptionPayment = apps.get_model("subscriptions", "SubscriptionPayment")
    for payment in SubscriptionPayment.objects.select_related("subscription").filter(
        business__isnull=True,
    ):
        payment.business_id = payment.subscription.business_id
        payment.save(update_fields=["business"])


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_allow_trial_plan_feature_ai_assistant_and_more'),
        ('tenants', '0004_businesssettings_more_option_label_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionpayment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='tenants.business'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(populate_payment_business, migrations.RunPython.noop),
    ]
