# Generated by Django 5.2.15 on 2026-07-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionpayment_reversal_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='feature_wms',
            field=models.BooleanField(default=False),
        ),
    ]
