# Generated by Django 5.2.15 on 2026-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_mode', models.CharField(choices=[('read_only', 'Read-only (view data, block new transactions)'), ('suspend', 'Full suspension (block all access)')], default='read_only', help_text='What happens to a business when its subscription expires.', max_length=12)),
            ],
            options={
                'verbose_name': 'platform configuration',
                'verbose_name_plural': 'platform configuration',
            },
        ),
    ]
