# Generated by Django 5.2.15 on 2026-07-15 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_initial'),
        ('sales', '0006_saleitem_actual_fabric_used_and_more'),
        ('suppliers', '0001_initial'),
        ('tenants', '0004_businesssettings_more_option_label_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], max_length=12),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('method', 'cheque'), ('cheque_status', ''), _connector='OR'), name='supplier_payment_status_cheque_only'),
        ),
    ]
