# Generated by Django 5.2.15 on 2026-07-24 22:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0006_business_onboarding_banner_dismissed_and_more"),
        ("wms_core", "0004_phase6_alteration_complete_permission"),
        ("wms_workforce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WmsAlteration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "original_order_reference",
                    models.CharField(max_length=80),
                ),
                (
                    "alteration_reference",
                    models.CharField(blank=True, max_length=80),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SIZE", "Size"),
                            ("DARAZ", "Daraz"),
                            ("FINISHING", "Finishing"),
                            ("BUTTON", "Button"),
                            ("VIP_DESIGN", "VIP Design"),
                            ("COMPUTER_DESIGN", "Computer Design"),
                            ("IRON", "Iron"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "mistake_by",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("CUSTOMER", "Customer"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("alteration_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "is_corrected",
                    models.BooleanField(default=False, editable=False),
                ),
                ("correction_reason", models.TextField(blank=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "assigned_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_alterations",
                        to="wms_workforce.wmsemployee",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.business",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wms_alterations_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wms_alterations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alterations",
                        to="wms_core.wmslocation",
                    ),
                ),
                (
                    "mistake_by_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alterations_mistake_by",
                        to="wms_workforce.wmsemployee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wms_alterations_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-alteration_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "alteration_date"],
                        name="wms_alt_business_date_idx",
                    ),
                    models.Index(
                        fields=[
                            "business",
                            "location",
                            "alteration_date",
                        ],
                        name="wms_alt_location_date_idx",
                    ),
                    models.Index(
                        fields=[
                            "business",
                            "assigned_employee",
                            "alteration_date",
                        ],
                        name="wms_alt_assigned_date_idx",
                    ),
                    models.Index(
                        fields=["business", "status", "alteration_date"],
                        name="wms_alt_status_date_idx",
                    ),
                    models.Index(
                        fields=["business", "reason", "alteration_date"],
                        name="wms_alt_reason_date_idx",
                    ),
                    models.Index(
                        fields=[
                            "business",
                            "original_order_reference",
                        ],
                        name="wms_alt_order_ref_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "reason__in",
                                (
                                    "SIZE",
                                    "DARAZ",
                                    "FINISHING",
                                    "BUTTON",
                                    "VIP_DESIGN",
                                    "COMPUTER_DESIGN",
                                    "IRON",
                                    "OTHER",
                                ),
                            )
                        ),
                        name="valid_wms_alteration_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ("OPEN", "IN_PROGRESS", "COMPLETED"),
                            )
                        ),
                        name="valid_wms_alteration_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("mistake_by", "EMPLOYEE"),
                                ("mistake_by_employee__isnull", False),
                            ),
                            models.Q(
                                (
                                    "mistake_by__in",
                                    ("CUSTOMER", "UNKNOWN"),
                                ),
                                ("mistake_by_employee__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="valid_wms_alteration_mistake",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", False),
                                ("status", "COMPLETED"),
                            ),
                            models.Q(
                                ("completed_at__isnull", True),
                                (
                                    "status__in",
                                    ("OPEN", "IN_PROGRESS"),
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="valid_wms_alteration_completion",
                    ),
                ],
            },
        ),
    ]
