# Generated by Django 5.2.15 on 2026-07-25 16:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_business_onboarding_banner_dismissed_and_more'),
        ('wms_attendance', '0001_initial'),
        ('wms_core', '0004_phase6_alteration_complete_permission'),
        ('wms_production', '0001_initial'),
        ('wms_workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('salary_year', models.PositiveSmallIntegerField()),
                ('salary_month', models.PositiveSmallIntegerField()),
                ('period_start', models.DateField(editable=False)),
                ('period_end', models.DateField(editable=False)),
                ('status', models.CharField(choices=[('CALCULATED', 'Calculated'), ('FINALIZED', 'Finalized')], default='CALCULATED', max_length=12)),
                ('employee_code_snapshot', models.CharField(editable=False, max_length=40)),
                ('employee_name_snapshot', models.CharField(editable=False, max_length=160)),
                ('employee_joining_date_snapshot', models.DateField(editable=False)),
                ('compensation_type_snapshot', models.CharField(choices=[('fixed_salary', 'Fixed Salary'), ('per_piece', 'Per Piece')], editable=False, max_length=20)),
                ('fixed_monthly_salary_snapshot', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=14, null=True)),
                ('default_per_piece_rate_snapshot', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=14, null=True)),
                ('currency_code_snapshot', models.CharField(editable=False, max_length=10)),
                ('currency_symbol_snapshot', models.CharField(blank=True, editable=False, max_length=10)),
                ('currency_precision_snapshot', models.PositiveSmallIntegerField(editable=False)),
                ('total_eligible_quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('gross_salary', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=18)),
                ('calculated_at', models.DateTimeField(editable=False)),
                ('finalized_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('calculated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_salaries_calculated', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='wms_workforce.wmsemployee')),
                ('finalized_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_salaries_finalized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-salary_year', '-salary_month', 'employee_name_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='WmsSalaryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('salary_date', models.DateField()),
                ('morning_status_snapshot', models.CharField(blank=True, editable=False, max_length=10)),
                ('evening_status_snapshot', models.CharField(blank=True, editable=False, max_length=10)),
                ('morning_time_in_snapshot', models.TimeField(blank=True, editable=False, null=True)),
                ('morning_time_out_snapshot', models.TimeField(blank=True, editable=False, null=True)),
                ('evening_time_in_snapshot', models.TimeField(blank=True, editable=False, null=True)),
                ('evening_time_out_snapshot', models.TimeField(blank=True, editable=False, null=True)),
                ('worked_minutes_snapshot', models.PositiveIntegerField(default=0, editable=False)),
                ('missing_minutes_snapshot', models.PositiveIntegerField(default=0, editable=False)),
                ('eligible_quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('daily_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=18)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_days', to='wms_attendance.wmsattendance')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_days', to='wms_core.wmslocation')),
                ('production_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_days', to='wms_production.wmsproductionentry')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='days', to='wms_salary.wmssalary')),
            ],
            options={
                'ordering': ['salary_date'],
            },
        ),
        migrations.CreateModel(
            name='WmsSalaryLocationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('location_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('location_type_snapshot', models.CharField(editable=False, max_length=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_location_snapshots', to='wms_core.wmslocation')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_snapshots', to='wms_salary.wmssalary')),
            ],
            options={
                'ordering': ['location_name_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='WmsSalaryPieceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('assignment_public_id_snapshot', models.UUIDField(editable=False)),
                ('category_name_snapshot', models.CharField(editable=False, max_length=100)),
                ('category_code_snapshot', models.CharField(blank=True, editable=False, max_length=40)),
                ('rate_source', models.CharField(choices=[('ASSIGNMENT', 'Assignment Override'), ('EMPLOYEE_DEFAULT', 'Employee Default')], editable=False, max_length=20)),
                ('applied_rate', models.DecimalField(decimal_places=3, editable=False, max_digits=14)),
                ('quantity', models.PositiveIntegerField(editable=False)),
                ('line_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=18)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_piece_lines', to='wms_production.wmsproductionentryline')),
                ('salary_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piece_lines', to='wms_salary.wmssalaryday')),
            ],
            options={
                'ordering': ['salary_day__salary_date', 'category_name_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='wmssalary',
            index=models.Index(fields=['business', 'salary_year', 'salary_month', 'status'], name='wms_salary_period_status_idx'),
        ),
        migrations.AddIndex(
            model_name='wmssalary',
            index=models.Index(fields=['business', 'employee', 'salary_year', 'salary_month'], name='wms_salary_emp_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmssalary',
            constraint=models.UniqueConstraint(fields=('business', 'employee', 'salary_year', 'salary_month'), name='uniq_wms_salary_emp_month'),
        ),
        migrations.AddConstraint(
            model_name='wmssalary',
            constraint=models.CheckConstraint(condition=models.Q(('salary_year__gte', 1), ('salary_year__lte', 9999)), name='valid_wms_salary_year'),
        ),
        migrations.AddConstraint(
            model_name='wmssalary',
            constraint=models.CheckConstraint(condition=models.Q(('salary_month__gte', 1), ('salary_month__lte', 12)), name='valid_wms_salary_month'),
        ),
        migrations.AddConstraint(
            model_name='wmssalary',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('CALCULATED', 'FINALIZED'))), name='valid_wms_salary_status'),
        ),
        migrations.AddConstraint(
            model_name='wmssalary',
            constraint=models.CheckConstraint(condition=models.Q(('total_eligible_quantity__gte', 0)), name='wms_salary_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wmssalary',
            constraint=models.CheckConstraint(condition=models.Q(('gross_salary__gte', 0)), name='wms_salary_gross_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='wmssalary',
            constraint=models.CheckConstraint(condition=models.Q(('currency_precision_snapshot__gte', 0), ('currency_precision_snapshot__lte', 3)), name='valid_wms_salary_precision'),
        ),
        migrations.AddConstraint(
            model_name='wmssalary',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('compensation_type_snapshot', 'fixed_salary'), ('default_per_piece_rate_snapshot__isnull', True), ('fixed_monthly_salary_snapshot__isnull', False)), models.Q(('compensation_type_snapshot', 'per_piece'), ('default_per_piece_rate_snapshot__isnull', False), ('fixed_monthly_salary_snapshot__isnull', True)), _connector='OR'), name='valid_wms_salary_comp'),
        ),
        migrations.AddConstraint(
            model_name='wmssalary',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finalized_at__isnull', True), ('finalized_by__isnull', True), ('status', 'CALCULATED')), models.Q(('finalized_at__isnull', False), ('status', 'FINALIZED')), _connector='OR'), name='valid_wms_salary_finalized'),
        ),
        migrations.AddIndex(
            model_name='wmssalaryday',
            index=models.Index(fields=['business', 'salary', 'salary_date'], name='wms_salary_day_date_idx'),
        ),
        migrations.AddIndex(
            model_name='wmssalaryday',
            index=models.Index(fields=['business', 'location', 'salary_date'], name='wms_salary_day_loc_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmssalaryday',
            constraint=models.UniqueConstraint(fields=('business', 'salary', 'salary_date'), name='uniq_wms_salary_day'),
        ),
        migrations.AddConstraint(
            model_name='wmssalaryday',
            constraint=models.CheckConstraint(condition=models.Q(('eligible_quantity__gte', 0)), name='wms_salary_day_qty_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='wmssalaryday',
            constraint=models.CheckConstraint(condition=models.Q(('daily_amount__gte', 0)), name='wms_salary_day_amt_nonneg'),
        ),
        migrations.AddIndex(
            model_name='wmssalarylocationsnapshot',
            index=models.Index(fields=['business', 'location', 'salary'], name='wms_salary_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmssalarylocationsnapshot',
            constraint=models.UniqueConstraint(fields=('business', 'salary', 'location'), name='uniq_wms_salary_location'),
        ),
        migrations.AddIndex(
            model_name='wmssalarypieceline',
            index=models.Index(fields=['business', 'salary_day'], name='wms_salary_piece_day_idx'),
        ),
        migrations.AddIndex(
            model_name='wmssalarypieceline',
            index=models.Index(fields=['business', 'production_line'], name='wms_salary_piece_src_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmssalarypieceline',
            constraint=models.UniqueConstraint(fields=('business', 'salary_day', 'production_line'), name='uniq_wms_salary_piece_line'),
        ),
        migrations.AddConstraint(
            model_name='wmssalarypieceline',
            constraint=models.CheckConstraint(condition=models.Q(('applied_rate__gte', 0)), name='wms_salary_rate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='wmssalarypieceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='wms_salary_piece_qty_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='wmssalarypieceline',
            constraint=models.CheckConstraint(condition=models.Q(('line_amount__gte', 0)), name='wms_salary_piece_amt_nonneg'),
        ),
    ]
