# Generated by Django 5.2.15 on 2026-08-17

from decimal import Decimal

import django.db.models.expressions
from django.db import migrations, models


def populate_salary_components(apps, schema_editor):
    salary_model = apps.get_model("wms_salary", "WmsSalary")
    salaries = salary_model.objects.using(schema_editor.connection.alias)
    salaries.filter(compensation_type_snapshot="fixed_salary").update(
        fixed_salary_component=models.F("gross_salary"),
        production_salary_component=Decimal("0.000"),
    )
    salaries.filter(compensation_type_snapshot="per_piece").update(
        fixed_salary_component=Decimal("0.000"),
        production_salary_component=models.F("gross_salary"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wms_salary", "0001_initial"),
        ("wms_workforce", "0002_hybrid_compensation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wmssalary",
            name="valid_wms_salary_comp",
        ),
        migrations.AddField(
            model_name="wmssalary",
            name="fixed_salary_component",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                editable=False,
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="wmssalary",
            name="production_salary_component",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                editable=False,
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="wmssalary",
            name="compensation_type_snapshot",
            field=models.CharField(
                choices=[
                    ("fixed_salary", "Fixed Salary"),
                    ("per_piece", "Per Piece"),
                    ("hybrid", "Hybrid (Fixed + Production)"),
                ],
                editable=False,
                max_length=20,
            ),
        ),
        migrations.RunPython(
            populate_salary_components,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="wmssalary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    fixed_salary_component__gte=0,
                    production_salary_component__gte=0,
                ),
                name="wms_salary_components_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmssalary",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        compensation_type_snapshot="fixed_salary",
                        production_salary_component=0,
                    )
                    | models.Q(
                        compensation_type_snapshot="per_piece",
                        fixed_salary_component=0,
                    )
                    | models.Q(compensation_type_snapshot="hybrid")
                ),
                name="wms_salary_component_types",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmssalary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    gross_salary=django.db.models.expressions.CombinedExpression(
                        models.F("fixed_salary_component"),
                        "+",
                        models.F("production_salary_component"),
                    )
                ),
                name="wms_salary_components_sum",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmssalary",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        compensation_type_snapshot="fixed_salary",
                        fixed_monthly_salary_snapshot__isnull=False,
                        default_per_piece_rate_snapshot__isnull=True,
                    )
                    | models.Q(
                        compensation_type_snapshot="per_piece",
                        fixed_monthly_salary_snapshot__isnull=True,
                        default_per_piece_rate_snapshot__isnull=False,
                    )
                    | models.Q(
                        compensation_type_snapshot="hybrid",
                        fixed_monthly_salary_snapshot__isnull=False,
                        default_per_piece_rate_snapshot__isnull=False,
                    )
                ),
                name="valid_wms_salary_comp",
            ),
        ),
    ]
