# Generated by Django 5.2.15 on 2026-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_business_onboarding_banner_dismissed_and_more"),
        (
            "wms_production",
            "0002_remove_wmsproductionentryline_uniq_wms_prod_entry_assignment_and_more",
        ),
        ("wms_salary", "0002_hybrid_compensation"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmssalarypieceline",
            name="order_public_id_snapshot",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="wmssalarypieceline",
            name="order_reference_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=80, null=True),
        ),
        migrations.AddConstraint(
            model_name="wmssalarypieceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("order_public_id_snapshot__isnull", True),
                        ("order_reference_snapshot__isnull", True),
                    ),
                    models.Q(
                        ("order_public_id_snapshot__isnull", False),
                        ("order_reference_snapshot__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="wms_salary_order_snapshot_pair",
            ),
        ),
    ]
