# Generated by Django 5.2.15 on 2026-07-24 20:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_business_onboarding_banner_dismissed_and_more'),
        ('wms_core', '0002_phase2_category_role_permissions'),
        ('wms_workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('production_date', models.DateField()),
                ('daily_total_pieces', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_corrected', models.BooleanField(default=False, editable=False)),
                ('correction_reason', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_production_entries_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='wms_workforce.wmsemployee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='wms_core.wmslocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_production_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-production_date', 'employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='WmsProductionEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('category_name_snapshot', models.CharField(editable=False, max_length=100)),
                ('category_code_snapshot', models.CharField(blank=True, editable=False, max_length=40)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lines', to='wms_workforce.wmsemployeecategoryassignment')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lines', to='wms_workforce.wmsproductioncategory')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='wms_production.wmsproductionentry')),
            ],
            options={
                'ordering': ['assignment__category__display_order', 'category_name_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='wmsproductionentry',
            index=models.Index(fields=['business', 'production_date'], name='wms_prod_business_date_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsproductionentry',
            index=models.Index(fields=['business', 'location', 'production_date'], name='wms_prod_location_date_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsproductionentry',
            index=models.Index(fields=['business', 'employee', 'production_date'], name='wms_prod_employee_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsproductionentry',
            constraint=models.UniqueConstraint(fields=('business', 'employee', 'production_date'), name='uniq_wms_production_employee_date'),
        ),
        migrations.AddConstraint(
            model_name='wmsproductionentry',
            constraint=models.CheckConstraint(condition=models.Q(('daily_total_pieces__gte', 0)), name='nonnegative_wms_daily_total'),
        ),
        migrations.AddIndex(
            model_name='wmsproductionentryline',
            index=models.Index(fields=['business', 'category'], name='wms_prod_line_category_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsproductionentryline',
            index=models.Index(fields=['business', 'assignment'], name='wms_prod_line_assign_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsproductionentryline',
            constraint=models.UniqueConstraint(fields=('business', 'entry', 'assignment'), name='uniq_wms_prod_entry_assignment'),
        ),
        migrations.AddConstraint(
            model_name='wmsproductionentryline',
            constraint=models.UniqueConstraint(fields=('business', 'entry', 'category'), name='uniq_wms_prod_entry_category'),
        ),
        migrations.AddConstraint(
            model_name='wmsproductionentryline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='nonnegative_wms_prod_quantity'),
        ),
    ]
