# Generated by Django 5.2.15 on 2026-09-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_business_onboarding_banner_dismissed_and_more"),
        ("wms_orders", "0002_wmsworkshoporder_eligible_piece_count_and_more"),
        ("wms_production", "0001_initial"),
        ("wms_workforce", "0002_hybrid_compensation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wmsproductionentryline",
            name="uniq_wms_prod_entry_assignment",
        ),
        migrations.RemoveConstraint(
            model_name="wmsproductionentryline",
            name="uniq_wms_prod_entry_category",
        ),
        migrations.AddField(
            model_name="wmsproductionentryline",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_lines",
                to="wms_orders.wmsworkshoporder",
            ),
        ),
        migrations.AddIndex(
            model_name="wmsproductionentryline",
            index=models.Index(
                fields=["business", "order", "category"], name="wms_prod_order_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wmsproductionentryline",
            index=models.Index(fields=["business", "order"], name="wms_prod_order_idx"),
        ),
    ]
