# Generated by Django 5.2.15 on 2026-07-13 19:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_tailoring_item'),
        ('suppliers', '0001_initial'),
        ('tenants', '0004_businesssettings_more_option_label_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_adult_fabric',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Estimated meters required for one adult garment.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000.000'))], verbose_name='Estimated Adult Fabric'),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_child_fabric',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Estimated meters required for one child garment.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000.000'))], verbose_name='Estimated Child Fabric'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_adult_fabric__isnull', True), models.Q(('estimated_adult_fabric__gte', 0), ('estimated_adult_fabric__lte', Decimal('1000.000'))), _connector='OR'), name='product_adult_fabric_valid'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_child_fabric__isnull', True), models.Q(('estimated_child_fabric__gte', 0), ('estimated_child_fabric__lte', Decimal('1000.000'))), _connector='OR'), name='product_child_fabric_valid'),
        ),
    ]
