# Generated by Django 5.2.15 on 2026-07-15 12:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('expenses', '0002_initial'),
        ('registers', '0001_initial'),
        ('sales', '0006_saleitem_actual_fabric_used_and_more'),
        ('suppliers', '0001_initial'),
        ('tenants', '0004_businesssettings_more_option_label_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='generated_for_month',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='RecurringExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('default_amount', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_templates', to='expenses.expensecategory')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_expenses', to='expenses.recurringexpensetemplate'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_template__isnull', False), ('generated_for_month__isnull', False)), fields=('recurring_template', 'generated_for_month'), name='uniq_recurring_expense_per_month'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('generated_for_month__isnull', True), ('recurring_template__isnull', True)), models.Q(('generated_for_month__isnull', False), ('recurring_template__isnull', False)), _connector='OR'), name='expense_recurring_provenance_pair'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpensetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('default_amount__gte', 0)), name='recurring_expense_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpensetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('due_day__gte', 1), ('due_day__lte', 31)), name='recurring_expense_due_day_range'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpensetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='recurring_expense_end_after_start'),
        ),
    ]
