# Generated by Django 5.2.15 on 2026-07-24 14:01

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_business_onboarding_banner_dismissed_and_more'),
        ('wms_core', '0002_phase2_category_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('employee_code', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=160)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('joining_date', models.DateField()),
                ('compensation_type', models.CharField(choices=[('fixed_salary', 'Fixed Salary'), ('per_piece', 'Per Piece')], max_length=20)),
                ('fixed_monthly_salary', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('default_per_piece_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_employees_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='wms_core.wmslocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_employees_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='WmsProductionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_categories_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_categories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WmsEmployeeCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('per_piece_rate', models.DecimalField(blank=True, decimal_places=3, help_text='Optional override; blank uses the employee default rate.', max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_assignments', to='wms_workforce.wmsemployee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_assignments_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='wms_workforce.wmsproductioncategory')),
            ],
            options={
                'ordering': ['category__display_order', 'category__name'],
            },
        ),
        migrations.AddIndex(
            model_name='wmsemployee',
            index=models.Index(fields=['business', 'is_active', 'full_name'], name='wms_emp_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsemployee',
            index=models.Index(fields=['business', 'location', 'is_active'], name='wms_emp_business_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsemployee',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('employee_code'), models.F('business'), name='uniq_wms_employee_code_ci_business'),
        ),
        migrations.AddConstraint(
            model_name='wmsemployee',
            constraint=models.CheckConstraint(condition=models.Q(('compensation_type__in', ('fixed_salary', 'per_piece'))), name='valid_wms_employee_comp_type'),
        ),
        migrations.AddConstraint(
            model_name='wmsemployee',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_monthly_salary__isnull', True), ('fixed_monthly_salary__gte', 0), _connector='OR'), name='nonnegative_wms_fixed_salary'),
        ),
        migrations.AddConstraint(
            model_name='wmsemployee',
            constraint=models.CheckConstraint(condition=models.Q(('default_per_piece_rate__isnull', True), ('default_per_piece_rate__gte', 0), _connector='OR'), name='nonnegative_wms_piece_rate'),
        ),
        migrations.AddConstraint(
            model_name='wmsemployee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('compensation_type', 'fixed_salary'), ('default_per_piece_rate__isnull', True), ('fixed_monthly_salary__isnull', False)), models.Q(('compensation_type', 'per_piece'), ('default_per_piece_rate__isnull', False), ('fixed_monthly_salary__isnull', True)), _connector='OR'), name='valid_wms_employee_comp_values'),
        ),
        migrations.AddIndex(
            model_name='wmsproductioncategory',
            index=models.Index(fields=['business', 'is_active', 'display_order', 'name'], name='wms_cat_active_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsproductioncategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('business'), name='uniq_wms_category_name_ci_business'),
        ),
        migrations.AddConstraint(
            model_name='wmsproductioncategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('business'), condition=models.Q(('code', ''), _negated=True), name='uniq_wms_category_code_ci_business'),
        ),
        migrations.AddIndex(
            model_name='wmsemployeecategoryassignment',
            index=models.Index(fields=['business', 'employee', 'is_active'], name='wms_assign_emp_active_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsemployeecategoryassignment',
            index=models.Index(fields=['business', 'category', 'is_active'], name='wms_assign_cat_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsemployeecategoryassignment',
            constraint=models.UniqueConstraint(fields=('business', 'employee', 'category'), name='uniq_wms_employee_category_business'),
        ),
        migrations.AddConstraint(
            model_name='wmsemployeecategoryassignment',
            constraint=models.CheckConstraint(condition=models.Q(('per_piece_rate__isnull', True), ('per_piece_rate__gte', 0), _connector='OR'), name='nonnegative_wms_assignment_rate'),
        ),
    ]
