# Generated by Django 5.2.15 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms_workforce", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wmsemployee",
            name="valid_wms_employee_comp_type",
        ),
        migrations.RemoveConstraint(
            model_name="wmsemployee",
            name="valid_wms_employee_comp_values",
        ),
        migrations.AlterField(
            model_name="wmsemployee",
            name="compensation_type",
            field=models.CharField(
                choices=[
                    ("fixed_salary", "Fixed Salary"),
                    ("per_piece", "Per Piece"),
                    ("hybrid", "Hybrid (Fixed + Production)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="wmsemployee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    compensation_type__in=(
                        "fixed_salary",
                        "per_piece",
                        "hybrid",
                    )
                ),
                name="valid_wms_employee_comp_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmsemployee",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        compensation_type="fixed_salary",
                        fixed_monthly_salary__isnull=False,
                        default_per_piece_rate__isnull=True,
                    )
                    | models.Q(
                        compensation_type="per_piece",
                        fixed_monthly_salary__isnull=True,
                        default_per_piece_rate__isnull=False,
                    )
                    | models.Q(
                        compensation_type="hybrid",
                        fixed_monthly_salary__isnull=False,
                        default_per_piece_rate__isnull=False,
                    )
                ),
                name="valid_wms_employee_comp_values",
            ),
        ),
    ]
