# Generated by Django 5.2.15 on 2026-07-24 19:30

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_business_onboarding_banner_dismissed_and_more'),
        ('wms_core', '0002_phase2_category_role_permissions'),
        ('wms_workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('attendance_date', models.DateField()),
                ('morning_time_in', models.TimeField(blank=True, null=True)),
                ('morning_time_out', models.TimeField(blank=True, null=True)),
                ('evening_time_in', models.TimeField(blank=True, null=True)),
                ('evening_time_out', models.TimeField(blank=True, null=True)),
                ('morning_shift_start', models.TimeField(editable=False)),
                ('morning_shift_end', models.TimeField(editable=False)),
                ('evening_shift_start', models.TimeField(editable=False)),
                ('evening_shift_end', models.TimeField(editable=False)),
                ('grace_period_minutes', models.PositiveIntegerField(editable=False)),
                ('morning_status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='absent', editable=False, max_length=10)),
                ('evening_status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='absent', editable=False, max_length=10)),
                ('morning_worked_minutes', models.PositiveIntegerField(default=0, editable=False)),
                ('evening_worked_minutes', models.PositiveIntegerField(default=0, editable=False)),
                ('worked_minutes', models.PositiveIntegerField(default=0, editable=False)),
                ('missing_minutes', models.PositiveIntegerField(default=0, editable=False)),
                ('correction_flag', models.BooleanField(default=False, editable=False)),
                ('correction_reason', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_attendance_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='wms_workforce.wmsemployee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='wms_core.wmslocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_attendance_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attendance_date', 'employee__full_name'],
                'indexes': [models.Index(fields=['business', 'attendance_date'], name='wms_att_business_date_idx'), models.Index(fields=['business', 'location', 'attendance_date'], name='wms_att_location_date_idx'), models.Index(fields=['business', 'employee', 'attendance_date'], name='wms_att_employee_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'employee', 'attendance_date'), name='uniq_wms_attendance_employee_date'), models.CheckConstraint(condition=models.Q(('morning_status__in', ('present', 'late', 'absent'))), name='valid_wms_morning_status'), models.CheckConstraint(condition=models.Q(('evening_status__in', ('present', 'late', 'absent'))), name='valid_wms_evening_status'), models.CheckConstraint(condition=models.Q(('worked_minutes', django.db.models.expressions.CombinedExpression(models.F('morning_worked_minutes'), '+', models.F('evening_worked_minutes')))), name='valid_wms_attendance_total')],
            },
        ),
    ]
